Fix/dependency vulnerability
aHub-Tech/hub-api pull request #22
Opened 2021-09-25 03:50 UTC by Isabelar07

fixes vulnerability of dependencies

2021-09-25 03:53 UTC, vcwild commented
Resolves #21

2021-09-25 04:27 UTC, DevRadhy approved these changes
ok

2021-09-25 22:35 UTC, vcwild approved these changes

2021-09-26 21:10 UTC, RodrigoDornelles requested changes
Eu não manjo tanto do eco sistema de javascript, mas apareceu alguns alertas de dependências ultrapassadas, consegue aferir o impacto e talvez corrigir? 
```
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated @types/mongoose@5.11.97: Mongoose publishes its own types, so you do not need to install this package.
```

2021-09-27 21:58 UTC, Isabelar07 commented
não estamos usando uuid, usamos o object_id do mongo. Não sei se object_id usa o uuid por debaixo dos panos, mas acredito que isso não vai impactar na api, assim como os demais. Mas posso "atualizar" se for o caso. Em relação ao type do mongoose, vou deixar com ele mesmo. O emídio tem mais experiência com mongo e nestjs do que eu, então acredito que ele colocou o type por algum motivo.

2021-09-27 22:33 UTC, RodrigoDornelles approved these changes
Aprovado então! deixo para o @caio-emidio considerar essas coisas futuramente!

2021-09-29 18:19 UTC, merged

2021-09-29 18:59 UTC, caio-emidio commented
Um esquema ali era ter dado upgrade e ver se vai dar B.O.